os: osx
osx_image: xcode10.1
language: objective-c
before_install:
- bash Scripts/decrypt.bash
install:
- carthage bootstrap
- bundle install
- gem install xcpretty-travis-formatter
script:
- xcodebuild -version
- xcodebuild
before_deploy:
- source Scripts/tag-beta.bash
- mkdir Upload
- cp build/Release/MetaZ-* Upload/
- ls Upload/
- rm Upload/MetaZ-*.xml
- mv Upload/MetaZ-*+dSYM.zip Upload/Debug.dSYM.zip
- mv Upload/MetaZ-*.json Upload/Sparkle.json
- rm Upload/*.dmg
#after_deploy:
#- bash Scripts/trigger-site.bash
deploy:
- provider: releases
  api_key:
    secure: "mHXHNMFb/Xpo9fvnYlGf7LGsRkaOtFwacH7QBHVkFDmdsv3/GrUa8D7fs8LLKkKpUiSczH81DmJD3rda2nQABXzDSp+h5iDVGicJNjifDn1GWyjXEPF+aQ8wj4JUUIvTO/y8P8US1UA3fUR3wKK5VsGHfuc41JHUd1di2uqr5ScMt33IEoI5j/f/WqKB5L0DaSjr9rnbkEOdh9nbUtmEc2PyihA87IRjt03HSVriq7EIxR0t2zEwzbOwHmciCrkPBt0aFNCC7jCxQyospv7kRyZJit0fNrmzuRZwJROlqh9zaPnx9++Krosp/O5GYX9dEbgAgey42W0JKCxH2fs1De9+lrXAJMIA1stICwYKFp9A+K+UmnL/34MAmp7tbK5uwkQgwciU0vVneEoPHyeDkJ2MqJvuKNyZZrvMkwkfR3QDUTamRa8DffdaajEFvCUK4Dk34pNmFrSZ4+S02H50gSnffUmU0uAhc/XnjWz5GJxcYjkhc37kKSLkoPz3asBv2CA0+UQmXmGt7CweHukMZ1F9gOQJIWa4+qorRld/CYDd2LchS17V2a9R698OUGergOvROOxqT5jhjcGm92B/0UVrIYZQ81tkhosaDPOpTmB/U5NndJvz8vmB2rTFamQzIpPxnyDCvQJuhUOE+Pn1N0RBf21QQSj0uUP+QPdel9k="
  file_glob: true
  file: Upload/*
  skip_cleanup: true
  prerelease: true
  name: $RELEASE_NAME
  on:
    branch: develop
- provider: releases
  api_key:
    secure: "mHXHNMFb/Xpo9fvnYlGf7LGsRkaOtFwacH7QBHVkFDmdsv3/GrUa8D7fs8LLKkKpUiSczH81DmJD3rda2nQABXzDSp+h5iDVGicJNjifDn1GWyjXEPF+aQ8wj4JUUIvTO/y8P8US1UA3fUR3wKK5VsGHfuc41JHUd1di2uqr5ScMt33IEoI5j/f/WqKB5L0DaSjr9rnbkEOdh9nbUtmEc2PyihA87IRjt03HSVriq7EIxR0t2zEwzbOwHmciCrkPBt0aFNCC7jCxQyospv7kRyZJit0fNrmzuRZwJROlqh9zaPnx9++Krosp/O5GYX9dEbgAgey42W0JKCxH2fs1De9+lrXAJMIA1stICwYKFp9A+K+UmnL/34MAmp7tbK5uwkQgwciU0vVneEoPHyeDkJ2MqJvuKNyZZrvMkwkfR3QDUTamRa8DffdaajEFvCUK4Dk34pNmFrSZ4+S02H50gSnffUmU0uAhc/XnjWz5GJxcYjkhc37kKSLkoPz3asBv2CA0+UQmXmGt7CweHukMZ1F9gOQJIWa4+qorRld/CYDd2LchS17V2a9R698OUGergOvROOxqT5jhjcGm92B/0UVrIYZQ81tkhosaDPOpTmB/U5NndJvz8vmB2rTFamQzIpPxnyDCvQJuhUOE+Pn1N0RBf21QQSj0uUP+QPdel9k="
  file_glob: true
  file: Upload/*
  skip_cleanup: true
  name: $RELEASE_NAME
  on:
    tags: true
branches:
  except:
  - /^v+[0-9]\.+[0-9]\.beta-+[0-9]/
env:
  global:
  - secure: N5QSC1Tg6X+bKZoKSoLcvlbWctgALdbGDArHQBekXHuRvAmiJev27eL1k7cMn4le4FeJEKOQHrL6TCLKW1R3bBwoGhn5VW06/Oq9p2SgDKmDhH65SyhhB7GP0QtPOzHx51VJxfOTcWHSAz4hTsNHdGPZVNb3EmOirUzu6jCD8MGvjRnwt2S6y7ZZrucb2cw0PgPIAJH1GTag3ZRM7VHx2ULtQ+B+fK+z2jJ2dRv2+nnOteuPLNrVnX3N1tP7nxV4eYrgCykaSNp952BcXpuObpPAHGSkIfpmtOQYFGZ5WuBCOguwDcvHzoJA8pEazDUf76jffZus0DM3AVQmyI7w4ZEsfhMtmZulawZa5nySLN01BwYOk8u5JpKworD2JQYfrU8WTPfwjplea7vu7pXcpt8ZV9Q9Ipe9k6GxnyAwV5fkgOTJ5ZsRnl6KmUMtPE8p0AtFy/KmpEh4SrnojlR/AT1om32g+HkaoMT90drxdm035GGWz+GvduEhkPTODRylSYDVgf+gCyhEWON4CaXfPvKrhqS/PprCQ5GqyRsofCXk9Pm4/jdeV0UMoam5v8yWTNordfCnMm2MBmLsGk4VkNE0ppHUTt9R4FXgaeUyfxapsabOYuO7kDPbrEJNXBXky/JGoN/LNhBRJ1Fqgrv+EWMdlNc/NNV8RR4oiZbkp9c=
  - secure: vIV8HFKzc4/i2DECgq/+XUYmqrB5fPf69fe0PQUuPdTwZm4esDPJ3qWOYoMzR1IYu0doyASIOYCV3gvVzi949PC0ld1t9sCMOEJnwnHfxA+D+tafUehao7GZlypUwnYRNc1Vm7AJI5n5oIpKiGiUn+azjQTNYFbpii5zQ6sWbgnjiPsSeBpe1ZfA8qB0ciVtKn60Hxd3aqgUHOBm5cjmcyA8xdWt/hRFh516j0LAph4GCZundx86vLZ1pWLrzdbiK0AK/LlpVGy5cGfLpkC2icn0pIqGDOOJ5ukKOHtt7+KueayMgttFp53T3EgeDxr7cNI48U6IzxxXlQrUBVfcvpxs46rQRS6cNJ5Qk0xR014MqMXK3v2cFlyzxbfXF53nq/jw5OcZrCnOvPiK3xT/+pPlHDgLo8GIgZ1P8c1AbzQlBnbhTZkgzvL0n3yN83esHOWp0WMQKBRYneDzyzfjg2kGOBV6qt6Y1BmqFxMvAC9MbWaQ692bsscXc3mtXAKl1brcarxzwrmQ1lRIuB0ha7koF20cxf+vdOMOgZqno2c12lqwMu5c+KNj3L18HGiEmdY4w7EiS139m5/1V+KYvjpPi3yt0rM0O1tDPdKK2Ecr2JEBppwHeSiivIyd04EJFn9E9T52W1fzN/Q7X1FK9d3EarEXtvI2/NfAKVbUM6I=
